/**
 * 빌드 타입별 전체 빌드 프로세스를 처리합니다.
 * config.ts 생성 → transpile → 이전 출력 폴더 삭제 → electron-builder → config.txt 생성
 *
 * 사용 예시 (Windows cmd):
 *   set BUILD_TYPE=prd&& node scripts/build.js
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const buildType = process.env.BUILD_TYPE || 'dev';
const { version } = require(path.join(ROOT, 'package.json'));

const urlMap = {
  local: 'http://192.168.10.34:4000/',
  dev: 'https://vco-api.dev.fainders.ai/',
  qa: 'https://vco-api.qa.fainders.ai/',
  prd: 'https://vco-api.fainders.ai/',
};

const folderMap = {
  local: `FAI VCO OKPOS Agent Local v${version}`,
  dev: `FAI VCO OKPOS Agent Dev v${version}`,
  qa: `FAI VCO OKPOS Agent QA v${version}`,
  prd: `FAI VCO OKPOS Agent v${version}`,
};

const url = urlMap[buildType];
const outputFolder = folderMap[buildType];

if (!url) {
  console.error(`[build] Unknown BUILD_TYPE: "${buildType}". Allowed: ${Object.keys(urlMap).join(', ')}`);
  process.exit(1);
}

// 1. config.ts 생성
const configContent = `// Auto-generated by scripts/build.js — DO NOT EDIT MANUALLY
// BUILD_TYPE: ${buildType}
export default {
  ERP_URL: "${url}",
  EXTERNAL_CODE: "056",
};
`;
fs.writeFileSync(path.join(ROOT, 'config.ts'), configContent);
console.log(`[build] BUILD_TYPE=${buildType} → ERP_URL=${url}`);
console.log(`[build] Output: ${outputFolder}`);

// 2. TypeScript 컴파일 및 파일 복사
console.log('[build] Transpiling...');
execSync('yarn transpile', { stdio: 'inherit', cwd: ROOT });

// 3. 이전 출력 폴더 삭제
const outputPath = path.join(ROOT, outputFolder);
if (fs.existsSync(outputPath)) {
  fs.rmSync(outputPath, { recursive: true, force: true });
  console.log(`[build] Cleaned: ${outputFolder}`);
}

// 4. electron-builder 실행
console.log('[build] Running electron-builder...');
execSync('electron-builder --config electron-builder.config.js', {
  stdio: 'inherit',
  cwd: ROOT,
  env: process.env,
});

// 5. config.txt 생성 (API_KEY 입력용 placeholder)
fs.writeFileSync(path.join(outputPath, 'config.txt'), '1234');
console.log(`[build] Done → ${outputFolder}`);
