/**
 * 빌드 타입에 맞는 ERP_URL을 config.ts에 주입합니다.
 * 빌드 스크립트에서 BUILD_TYPE 환경변수를 설정한 후 호출됩니다.
 *
 * 사용 예시:
 *   set BUILD_TYPE=prd&& node scripts/set-env.js
 */

const fs = require('fs');
const path = require('path');

const buildType = process.env.BUILD_TYPE || 'dev';

const urlMap = {
  local: 'http://192.168.10.34:4000/',
  dev: 'https://vco-api.dev.fainders.ai/',
  qa: 'https://vco-api.qa.fainders.ai/',
  prd: 'https://vco-api.fainders.ai/',
};

const url = urlMap[buildType];

if (!url) {
  console.error(`[set-env] Unknown BUILD_TYPE: "${buildType}". Allowed: ${Object.keys(urlMap).join(', ')}`);
  process.exit(1);
}

const content = `// Auto-generated by scripts/set-env.js — DO NOT EDIT MANUALLY
// BUILD_TYPE: ${buildType}
export default {
  ERP_URL: "${url}",
  EXTERNAL_CODE: "056",
};
`;

fs.writeFileSync(path.join(__dirname, '..', 'config.ts'), content);
console.log(`[set-env] BUILD_TYPE=${buildType} → ERP_URL=${url}`);
